<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<Nullable>enable</Nullable>
		<TargetFramework>net8.0-windows</TargetFramework>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<Version>4.0.0</Version>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<!-- Konfiguration nur für Release-Build -->
	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SelfContained>true</SelfContained>
		<PublishSingleFile>true</PublishSingleFile>
		<PublishDir>dist\</PublishDir>
		<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
		<PublishTrimmed>false</PublishTrimmed>
		<!-- wichtig für WinForms/Reflection -->
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="SharpCompress" Version="0.48.1" />
	</ItemGroup>

	<!-- Expose internal helper methods to the unit test project only. -->
	<ItemGroup>
		<InternalsVisibleTo Include="BioLogicZipper.Tests" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="BioLogicZipper.Tests\**\*.cs" />
	</ItemGroup>

</Project>


